### ISSUE TITLE
Area of MGRS tiles

### ISSUE THREAD

**Issue by openpencil** [hrbrmstr/mgrs#1]
Dear Bob,
Thank you so very much for the mgrs package! I am doing a number of spatial aggregations in my current projects and your package has been extremely helpful. 

I was wondering if you would help me with this question. Since the MGRS system is not an equal-area gridding system, the area of individual MGRS tiles at the same resolution (10m^2, 100m^2 etc.) differ from each other. Do you know where I can find the actual area of each MGRS tile? 

Thanks very much for your time!
Best,
Jyoti

**Comment by hrbrmstr** [comment]
Many thanks for the taking the pkg for a spin and for the kind words!

Take a look at the extremely new `mgrs_precision()` function. The manual page for it explains what it does. Hopefully it'll be of use for this. You are correct in that the squares are of equal resolution.
