### ISSUE TITLE
Release packaged version

### ISSUE THREAD

**Issue by agcopenhaver** [hrbrmstr/mgrs#4]
Hi there-

Would you be able to release this as a versioned tar.gz? I'm trying to add it to conda-forge, so more people can access it easily, but in order to do that, I need a tarball and a version number.

Thanks in advance,

Andrew

**Comment by hrbrmstr** [comment]
Glad to! I cleaned up the README a bit to conform to my other recent pkg releases and did a minor version bump. 

https://github.com/hrbrmstr/mgrs/releases/tag/v0.2.1
