### ISSUE TITLE
Error in FUN(X[[i]], ...) :    tinyformat: Too many conversion specifiers in format string

### ISSUE THREAD

**Issue by tknoch8** [hrbrmstr/mgrs#5]
`clean_data %>% 
mutate(x = lapply(MGRS, mgrs::mgrs_to_latlng, include_mgrs_ref = FALSE)) %>% 
tidyr::unnest(x) -> new_df`
results in "Error in FUN(X[[i]], ...) : tinyformat: Too many conversion specifiers in format string"
I am not familiar with this error, I'm not sure where to go from here. Thanks!

**Comment by hrbrmstr** [comment]
Thx for kicking the tyres and taking the time to submit an issue!

Can you provide the output of `dput(clean_data$MGRS)` in a code block? I can run it locally and then see which ones are causing my code to cause that error.

**Comment by hrbrmstr** [comment]
#ty for the (offline) data! 

I did a tidy-less:

```r
mgrs_to_latlng(mg$MGRS, include_mgrs_ref = FALSE)
```
and saw this warning message that was built into the processing loop in my C++ code:

>Warning message:
>In mgrs_to_latlng(mg$MGRS, include_mgrs_ref = FALSE) :
>  One or more errors encounterd while converting 191399890 MGRS input strings

I'll respond privately with which ones (they are `NA` in the resultant data frame) and now I'll try it with the tidyverse idiom you did.

**Comment by hrbrmstr** [comment]
One pre-emptive thought before I start crunching (which I may have to stop soon as I'm abt to be in travel mode for 48hrs): Give this a try:

```r
clean_data %>% 
  bind_cols(
    mgrs::mgrs_to_latlng(.$MGRS, include_mgrs_ref = FALSE)
  ) -> new_df
```

Not only should it be much, _much_ faster, it may not toss those errors.

Also, if you still get anything besides a warning for those few, invalid MGRS strings, can you send me your `sessionInfo()` output (here or to the email thread)? #tyia

**Comment by hrbrmstr** [comment]
Take a look at the update I just pushed. I think I found and fixed the bug.
