### ISSUE TITLE
Problem Installing Package 

### ISSUE THREAD

**Issue by gl-smith** [hrbrmstr/mgrs#7]
I am currently unable to install this package after attempting to install it in a new version of R.  The error says that `'PI'` is an `undeclared identifier`. The full error message has been included below. I believe the error occurs for each of the main functions included in the `src/main.cpp` file. 

I received the same message for each of the following commands:

```
remotes::install_github("hrbrmstr/mgrs")

install.packages("mgrs", repos = "https://cinc.rud.is")

```

```
`main.cpp:41:42: error: use of undeclared identifier 'PI'
      lat_vec[i] = degrees ? lat * 180.0/PI : lat;
                                         ^

main.cpp:42:42: error: use of undeclared identifier 'PI'
      lng_vec[i] = degrees ? lng * 180.0/PI : lng;
                                         ^

main.cpp:86:17: error: use of undeclared identifier 'PI'
    latitude *= PI / 180.0;
                ^

main.cpp:87:18: error: use of undeclared identifier 'PI'
    longitude *= PI / 180.0;
                 ^

main.cpp:322:40: error: use of undeclared identifier 'PI'
      _["lat"] = degrees ? lat * 180.0/PI : lat,
                                       ^

main.cpp:323:40: error: use of undeclared identifier 'PI'
      _["lng"] = degrees ? lng * 180.0/PI : lng
                                       ^

main.cpp:361:40: error: use of undeclared identifier 'PI'
      _["lat"] = degrees ? lat * 180.0/PI : lat,
                                       ^

main.cpp:362:40: error: use of undeclared identifier 'PI'
      _["lng"] = degrees ? lng * 180.0/PI : lng
                                       ^

8 errors generated.
make: *** [main.o] Error 1
ERROR: compilation failed for package ‘mgrs’` 
```

My R and system information is included below. I also received the same error after trying to install the package on a Posit Cloud Installation. I have used this package extensively on previous versions of R and never had this issue. 

```
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid    
```

Thank you for your help and suggestions! This package has been incredibly helpful for my research!

**Comment by gl-smith** [comment]
To follow up with this, a colleague helped identify the problem in the `main.cpp` script. The script should work if `PI` is replaced with `M_PI`. I believe that url link below provides a bit more on the problem. Thank you again for your work on this package!  

[https://stackoverflow.com/questions/15231466/whats-the-difference-between-pi-and-m-pi-in-objc](url)

**Comment by hrbrmstr** [comment]
taking a loon rn

**Comment by hrbrmstr** [comment]
fixed (hopefully). It was defined in `utm.c` so I just moved it over to `utm.h`. Not sure how it was working now, before, tbh.

**Comment by gl-smith** [comment]
Awesome. Thanks for the help with this!!
